apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: sanjaysaini2000/react-app
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: todo-svc
spec:
  type: LoadBalancer
  selector:
    app: todo
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
